steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Run the build script (defined in your package.json)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Deploy to App Engine (using the default service)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

  # Deploy to App Engine (using a specific service - e.g., debug-service)
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['app', 'deploy', '--service=debug-service', '--quiet']

timeout: '600s' # Optional: Increase timeout if your build takes longer than 10 minutes (default)
